"""Initial_db

Revision ID: c74de0189c21
Revises: 
Create Date: 2021-05-06 16:39:11.512346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74de0189c21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neologism',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neologism', sa.String(), nullable=True),
    sa.Column('description', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('example', sa.String(), nullable=True),
    sa.Column('s_term', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neologism')
    # ### end Alembic commands ###
